version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'my-secret-pw'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  app:
    build: .
    environment:
      DB_URL: db
      DB_NAME: test
      DB_USERNAME: user
      DB_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8080:8080"
    expose:
      - '8080'
volumes:
  my-db: