apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-app-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-app-service
            port:
              number: 8080
        path: /
        pathType: Prefix
